---
title: "Sleep Report"
output:
  word_document:
    highlight: tango
    reference_docx: template.docx
params:
  binfile: NA
  summary_name: NA
  timer: True
---

```{r setup, include = FALSE}
timer <- params$timer
# timer = TRUE # For Manual Testing and vebrose mode remove comment
if (timer) {
  knitr::opts_chunk$set(
    echo = TRUE,
    warning = FALSE,
    message = FALSE,
    eval = TRUE,
    results = "show",
    fig.align = "center",
    fig.height = 8,
    fig.width = 14
  )
  times = time_stage = c()
  times = append(times, Sys.time())
  time_stage = append(time_stage, paste0("Start of File"))
} else {
  knitr::opts_chunk$set(
    echo = FALSE,
    warning = FALSE,
    message = FALSE,
    eval = TRUE,
    results = "hide",
    fig.align = "center",
    fig.height = 8,
    fig.width = 14
  )
}
```

```{r parameters}
UpDown.mad_plot_switch <- TRUE
daily_plot_switch <- TRUE
daily_summary_switch <- TRUE
device_details_switch <- TRUE
sleep_interruptions_switch <- TRUE

binfile <- params$binfile
summary_name <- params$summary_name
mmap.load <- FALSE
datacols <- c(
  "UpDown.mean", "UpDown.var", "UpDown.mad",
  "Degrees.mean", "Degrees.var", "Degrees.mad",
  "Magnitude.mean",
  "Light.mean",
  "Temp.mean", "Temp.sumdiff", "Temp.abssumdiff"
  # "Step.GENEAcount", "Step.sd", "Step.mean", "Step.median",
  # "Principal.Frequency.mean", "Principal.Frequency.median"
)

start_time <- "15:00"
```

```{r Manual parameters, eval = FALSE}
library(GENEAread)
library(GENEAclassify)
library(knitr)
library(ggplot2)
library(scales)
library(reshape2)

# Functions to use.

source("Functions/01_library_installer.R")
source("Functions/02_combine_segment_data.R")
source("Functions/03_naming_protocol.R")
source("Functions/04_create_df_pcp.R")
source("Functions/05_number_of_days.R")
source("Functions/06_bed_rise_detect.R")
source("Functions/07_state_rearrange.R")
source("Functions/08_UpDown.mad_plot.R")
source("Functions/090_daily_plot.R")
source("Functions/091_sleep_positionals.R")
source("Functions/092_light_temp.R")
source("Functions/093_hypnogram.R")
source("Functions/10_sleep_summary.R")

i <- 1
file_pattern <- "*\\.[bB][iI][nN]$"
files <- list.files(path = paste0(getwd(), "/Data"), pattern = file_pattern, full.names = TRUE)
binfile <- files[i]
summary_name <- paste0("Sleep_Summary_Metrics_", strsplit(unlist(strsplit(binfile, "/"))[length(unlist(strsplit(binfile, "/")))], ".bin")[[1]])
timer <- TRUE
datacols <- c(
  "UpDown.mean", "UpDown.var", "UpDown.sd",
  "Degrees.mean", "Degrees.var", "Degrees.sd",
  "Magnitude.mean", "Magnitude.var", "Magnitude.meandiff", "Magnitude.mad",
  "Light.mean", "Light.max",
  "Temp.mean", "Temp.sumdiff", "Temp.meandiff", "Temp.abssumdiff",
  "Temp.sddiff", "Temp.var", "Temp.GENEAskew", "Temp.mad"
  # "Step.GENEAcount", "Step.sd", "Step.mean", 
  # "Principal.Frequency.mean", "Principal.Frequency.median"
)

start_time <- "15:00"
```

```{r Combining and Classifying segmented data}
if (timer) {
  # Starting the timer
  cat("
      #. Start of Segmenting data")
  print(Sys.time())
  times = append(times, Sys.time())
  time_stage = append(time_stage, paste0("Start of Segmenting data"))
}

# Segment the data.
segment_data <- combine_segment_data(binfile,
  start_time,
  datacols,
  mmap.load = mmap.load
)

# Routine to remove overlap segments.
k = 1 # Counter
collen = length(segment_data$Start.Time)
overlap_list = which(segment_data$Start.Time[1:(collen - k)] > segment_data$Start.Time[(k+1):collen])

while (length(overlap_list) > 0){
  segment_data = segment_data[-overlap_list,]
  k = k + 1 
  overlap_list = which(segment_data$Start.Time[1:(collen - (k))] > segment_data$Start.Time[(k+1):collen])
}

data_name <- naming_protocol(binfile)

saveRDS(segment_data, file.path(getwd(), "/Outputs/", data_name))

# Write out the version of data that we want people to see
csvname <- naming_protocol(binfile, suffix = "_All_Data.csv")

write.csv(segment_data,
  file = file.path(paste0("Outputs/", csvname))
)
```

```{r Create_df_pcp function}
if (timer) {
  # Starting the timer
  cat("
      #. Deciding on classes")
  print(Sys.time())
  times = append(times, Sys.time())
  time_stage = append(time_stage, paste0("Deciding on Classes"))
}

segment_data_reduced <- segment_data[segment_data$Segment.Duration > 0,]

df_pcp <- create_df_pcp(segment_data_reduced,
  summary_name,
  # r Cut_points
  Magsa_cut = 0.04, # 40mg

  Duration_low  = exp(5.5),
  Duration_high = exp(8),

  Mad.Score2_low  = 0.45,
  Mad.Score2_high = 5,

  Mad.Score4_low  = 0.45,
  Mad.Score4_high = 5,

  Mad.Score6_low  = 0.45,
  Mad.Score6_high = 5,

  Mad_low  = 0.45,
  Mad_high = 5
)

# Add the additional class onto the end.
segment_data_reduced$Class.prior <- segment_data_reduced$Class.current <- segment_data_reduced$Class.post <- 2
# Create the correct classes for post and priors.
segment_data_reduced$Class.prior[1:(length(segment_data_reduced$Class.prior) - 2)] <- df_pcp$Class.current
segment_data_reduced$Class.current[2:(length(segment_data_reduced$Class.prior) - 1)] <- df_pcp$Class.current
segment_data_reduced$Class.post[3:(length(segment_data_reduced$Class.prior))] <- df_pcp$Class.current

segment_data <- segment_data_reduced

# # Once we've created a sleep score write out the data here. No longer need to save this
# saveRDS(df_pcp,
#         file = file.path(paste0("Outputs/", summary_name, "pcp.rds")))
```

```{r Number of days function}
no_days <- number_of_days(binfile,  start_time)
```

```{r Bed Rise Detection}
if (timer) {
  # Starting the timer
  cat("
      #. Start of Bed Rise Algorithm")
  print(Sys.time())
  times = append(times, Sys.time())
  time_stage = append(time_stage, paste0("Start of Bed Rise Algorithm"))
}

# Now check to see if there is a sleep_diary 
Sleep_Diary = NA

try({
  # Checking to find if there is a corresponding sleep diary 
  binfile_stripped = unlist(strsplit(binfile, "/"))
  binfile_stripped = binfile_stripped[length(binfile_stripped)]
  binfile_stripped = unlist(strsplit(binfile_stripped, ".bin"))
  
  Sleep_Diary = read.csv(paste0("Sleep_Diaries/", binfile_stripped, "_Sleep_Diary.csv"))
})

# Find the Bed and Rise times
bed_rise_df <- bed_rise_detect(binfile,
                               df_pcp,
                               no_days,
                               Sleep_Diary,
                               verbose = FALSE
)
```

```{r Initialising parameters required}

t <- as.POSIXct(as.numeric(as.character(segment_data$Start.Time[1])), origin = "1970-01-01")
first_date <- as.Date(t)
min_boundary <- max_boundary <- c()

for (i in 1:(no_days)) {
  min_boundary[i] <- as.POSIXct(as.character(paste(first_date + i - 1, start_time)), format = "%Y-%m-%d %H:%M", origin = "1970-01-01")
  max_boundary[i] <- as.POSIXct(as.character(paste(first_date + i, start_time)), format = "%Y-%m-%d %H:%M", origin = "1970-01-01")
}

boundarys <- cbind(min_boundary, max_boundary)

header <- header.info(binfile)
```

```{r State Rearrange}
# Use the Bed Rise rules to determine what state this will
segment_data <- state_rearrange(
  segment_data,
  boundarys,
  bed_rise_df$bed_time,
  bed_rise_df$rise_time,
  first_date
)

# # Write out the version of data that we want people to see
# csvname <- naming_protocol(binfile, suffix = "_States_Added_All_Data.csv")
# 
# write.csv(segment_data,
#   file = file.path(paste0("Outputs/", csvname))
# )
```

```{r UpDown.Mad Plot, results = 'asis'}

if (UpDown.mad_plot_switch) {
  if (timer) {
    # Starting the timer
    cat("
        #. UpDownMad Plot")
    print(Sys.time())
    times = append(times, Sys.time())
    time_stage = append(time_stage, paste0("UpDownMad Plot"))
  }

  UpDown.mad_plot(
    binfile,
    segment_data,
    start_time,
    no_days,
    bed_rise_df$bed_time,
    bed_rise_df$rise_time
  )
}
```

```{r Daily Plots}

if (daily_plot_switch) {
  #### For Loop ####
  for (i in 1:(no_days)) {
    if (timer) {
      # Starting the timer
      cat("
          #. Time of Day ", i, " plot creation is ")
      print(Sys.time())
      times = append(times, Sys.time())
      time_stage = append(time_stage, paste0("Daily Plot: ", i))
    }
    
    # Read in the AccData
    AccData <- read.bin(binfile,
      downsample = as.numeric(unlist(header$Value[2])),
      start = paste0((i - 1), " 15:00"),
      end = paste0(i, " 15:00"),
      mmap.load = mmap.load
    )

    # Now find the data between the threshold
    tmp_segment_data <- segment_data[segment_data$Start.Time > min_boundary[i] &
                                     segment_data$Start.Time < max_boundary[i], ]

    daily_plot(
      AccData, 
      segment_data = tmp_segment_data, 
      boundarys = boundarys[i, ],
      bed_time  = bed_rise_df$bed_time[i],
      rise_time = bed_rise_df$rise_time[i],
      first_date
    )
  }
}
```

```{r Summary header, results = 'asis'}
if (daily_summary_switch == TRUE) {
  cat("##### Daily Summary.")
  if (timer) {
    # Starting the timer
    cat("
        #. Time at start of stats table ")
    print(Sys.time())
    times = append(times, Sys.time())
    time_stage = append(time_stage, paste0("Sleep Summary"))
  }
}
```

```{r Summary table, results = 'asis'}
if (daily_summary_switch == TRUE) {
  
  statistics <- sleep_summary(bed_rise_df,
                              first_date)

  print(knitr::kable(statistics))

  write.csv(statistics, file.path(paste0("Outputs/", summary_name, ".csv")), row.names = FALSE)
  
}
```

```{r Device Details Header, results = 'asis'}
if (device_details_switch) {
  cat("##### Device Details.")
}
```

```{r Device Details Summary, results = 'markdown'}
if (device_details_switch) {
  if (timer) {
    # Starting the timer
    cat("
        #. Start of creating device details ")
    print(Sys.time())
    times = append(times, Sys.time())
    time_stage = append(time_stage, paste0("Device Details"))
  }

  h <- header.info(binfile)

  Title <- "Sleep Report"
  Date_Created <- as.character(Sys.Date())
  Binfile <- binfile
  Analysis_Code <- "0.1"
  Subject_Code <- unlist(h[[1]][10])
  Serial_Code <- unlist(h[[1]][11])
  Date_Of_Birth <- unlist(h[[1]][11])
  Sex <- unlist(h[[1]][12])
  height_m <- unlist(h[[1]][13])
  weight_kg <- unlist(h[[1]][14])
  handedness <- unlist(h[[1]][15])
  Original_sample_frequency_Hz <- unlist(h[[1]][2])
  Start_Time <- unlist(h[[1]][4])
  Measurement_period <- unlist(h[[1]][3])

  Title <- c(
    "Date_Created",
    "Binfile",
    "Analysis_Code_Version",
    "Subject_Code",
    "Serial_Code",
    "Date_Of_Birth",
    "Sex",
    "height_m",
    "weight_kg",
    "handedness",
    "Original_sample_frequency_Hz",
    "Start_Time",
    "Measurement_period"
  )

  Sleep_Report <- c(
    Date_Created,
    Binfile,
    Analysis_Code,
    Subject_Code,
    Serial_Code,
    Date_Of_Birth,
    Sex,
    height_m,
    weight_kg,
    handedness,
    Original_sample_frequency_Hz,
    Start_Time,
    Measurement_period
  )

  # Add Text on the csv
  # text = " "
  # write.table( text,
  #              file = file.path(paste0("Outputs/",summary_name, ".csv")),
  #              append = T,
  #              sep=',',
  #              row.names=F,
  #              col.names=F )

  Title_Page <- data.frame(Title, Sleep_Report)
  knitr::kable(Title_Page)

  # Add the details onto the csv

  # write.table( Title_Page,
  #              file = file.path(paste0("Outputs/",summary_name, ".csv")),
  #              append = T,
  #              sep=',',
  #              row.names=F,
  #              col.names=F )
}
```

```{r Sleep Interruptions Header, results = 'asis'}
if (sleep_interruptions_switch) {
  cat("##### Sleep interruptions")
}
```

```{r Sleep Interruptions Summary}

if (sleep_interruptions_switch) {

    if (timer) {
    # Starting the timer
    cat("
          #. Start of creating Sleep interruptions ")
    print(Sys.time())
    times = append(times, Sys.time())
    time_stage = append(time_stage, paste0("Sleep interruptions"))
    }
  
  ## Now adding in the next line as sleep interruptions each night. This can be done from the posture changes
  # Add Text on the csv
  text <- " "
  write.table(text,
              file = file.path(paste0("Outputs/", summary_name, ".csv")),
              append = T,
              sep = ",",
              row.names = F,
              col.names = F
  )
  
  text <- "Sleep Interruptions through each night"
  write.table(text,
              file = file.path(paste0("Outputs/", summary_name, ".csv")),
              append = T,
              sep = ",",
              row.names = F,
              col.names = F
  )
  
  for (j in 1:length(bed_rise_df$bed_time)) {
    # Skipping variable
    Skipping <- FALSE
    
    df <- segment_data[segment_data$Start.Time > bed_rise_df$bed_time[j] &
                       segment_data$Start.Time < bed_rise_df$rise_time[j], ]
    
    # Sleep Interruptions - From SIN, Inactive or Active class
    sleep_interruptions <- df[df$Class.current == 2 |
                              df$Class.current == 3 |
                              df$Class.current == 4, ]
    
    # If no interruptions
    if (length(df$Start.Time) == 0 | is.null(df) == TRUE) {
      Sleep_List <- c(as.character(j), "No interruptions")
      # Now writing these lines under the Date
      write.table(t(Sleep_List),
                  file = file.path(paste0("Outputs/", summary_name, ".csv")),
                  append = T,
                  sep = ",",
                  row.names = F,
                  col.names = F
      )
      next
    } else {
      write.table(sleep_interruptions,
                  file = file.path(paste0("Outputs/", summary_name, ".csv")),
                  append = T,
                  sep = ",",
                  row.names = F,
                  col.names = F)
    }
  }
}
```

```{r Outputing timer csv}
if (timer){
      cat("
        #. End of analysis for file ", binfile)
    print(Sys.time())
  times = as.numeric(append(times, Sys.time()))
  time_stage = append(time_stage, paste0("End of File"))
  timing_csv_name = naming_protocol(binfile, prefix = "", suffix = "_Time_Analysis_Report.csv")
  time_df = data.frame(times, time_stage)
  write.csv(time_df, timing_csv_name)
}
```
